-- Create Wishlist table
CREATE TABLE IF NOT EXISTS `Wishlist` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `MaTK` INT(6) ZEROFILL NOT NULL,
  `MaSP` VARCHAR(6) NOT NULL,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `MaTK_MaSP` (`MaTK`, `MaSP`),
  CONSTRAINT W_MaTK_FK FOREIGN KEY (MaTK) REFERENCES Account(MaTK) ON DELETE CASCADE,
  CONSTRAINT W_MaSP_FK FOREIGN KEY (MaSP) REFERENCES Products(MaSP) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
